// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElUpload: typeof import('element-plus/es')['ElUpload']
}
export {}
